2024-11-21 14:30:08 - root - ERROR - exception Details
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive\Desktop\New folder\Restaurant_Management_System\Src\Order_management\order_features.py", line 50, in take_order
    quantity = int(input("Enter quantity: "))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '@'
2024-11-21 14:30:24 - root - ERROR - exception Details
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive\Desktop\New folder\Restaurant_Management_System\Src\Order_management\order_features.py", line 50, in take_order
    quantity = int(input("Enter quantity: "))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '@'
2024-11-21 15:16:47 - root - ERROR - exception Details
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive\Desktop\New folder\Restaurant_Management_System\Src\Order_management\order_features.py", line 50, in take_order
    quantity = int(input("Enter quantity: "))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '@'
2024-11-21 15:17:12 - root - ERROR - exception Details
Traceback (most recent call last):
  File "c:\Users\DELL\OneDrive\Desktop\New folder\Restaurant_Management_System\Src\Order_management\order_features.py", line 50, in take_order
    quantity = int(input("Enter quantity: "))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '#'
2024-11-30 13:12:07 - root - ERROR - Error occurred while loading data: Failed to load the required database file.
2024-11-30 13:12:30 - root - ERROR - Error occurred while loading data: Failed to load the required database file.
2024-11-30 13:12:39 - root - ERROR - Error occurred while loading data: Failed to load the required database file.
